#define printf pspDebugScreenPrintf
#define TextColor(color) pspDebugScreenSetTextColor(color)
#define BackColor(color) pspDebugScreenSetBackColor(color)
#define RED 0xff0000ff
#define BLUE 0xffff0000
#define GREEN 0xff00ff00
#define LGRAY 0xffd3d3d3
#define WHITE 0xffffffff
#define BLACK 0x00000000
#define YELLOW 0xff00ffff
#define ORANGE 0xff007fff